dist: focal
language: java
jdk:
- openjdk11
before_install:
- openssl aes-256-cbc -K $encrypted_fb8a77c74dbd_key -iv $encrypted_fb8a77c74dbd_iv
  -in codesigning.asc.enc -out ./codesigning.asc -d
- sudo apt-get update
- export GPG_TTY=$(tty)
- gpg2 --batch --fast-import codesigning.asc
- nvm install --lts
cache:
  directories:
  - react/node_modules
  - "$HOME/.m2/repository"
script:
- cd react
- npm ci
- npm run build
- cd ..
- cp -a react/build/. webapp/src/main/webapp
- cd webapp
- mvn clean install -DskipTests -Dgpg.skip=true
# - mvn deploy -DskipTests --settings mvn-settings.xml
